# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/a_star.ui',
# licensing of './UI/a_star.ui' applies.
#
# Created: Tue May 28 17:02:06 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AStar(object):
    def setupUi(self, AStar):
        AStar.setObjectName("AStar")
        AStar.setWindowModality(QtCore.Qt.NonModal)
        AStar.setEnabled(True)
        AStar.resize(781, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/root/favicon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AStar.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AStar)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_row = QtWidgets.QLabel(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_row.setFont(font)
        self.label_row.setObjectName("label_row")
        self.horizontalLayout.addWidget(self.label_row)
        self.spinBox_row = QtWidgets.QSpinBox(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.spinBox_row.setFont(font)
        self.spinBox_row.setObjectName("spinBox_row")
        self.horizontalLayout.addWidget(self.spinBox_row)
        self.label_col = QtWidgets.QLabel(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_col.setFont(font)
        self.label_col.setObjectName("label_col")
        self.horizontalLayout.addWidget(self.label_col)
        self.spinBox_col = QtWidgets.QSpinBox(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.spinBox_col.setFont(font)
        self.spinBox_col.setObjectName("spinBox_col")
        self.horizontalLayout.addWidget(self.spinBox_col)
        self.pushButtonGenerate = QtWidgets.QPushButton(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.pushButtonGenerate.setFont(font)
        self.pushButtonGenerate.setObjectName("pushButtonGenerate")
        self.horizontalLayout.addWidget(self.pushButtonGenerate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonResult = QtWidgets.QPushButton(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.pushButtonResult.setFont(font)
        self.pushButtonResult.setObjectName("pushButtonResult")
        self.horizontalLayout.addWidget(self.pushButtonResult)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_setting = QtWidgets.QLabel(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_setting.setFont(font)
        self.label_setting.setObjectName("label_setting")
        self.horizontalLayout_3.addWidget(self.label_setting)
        self.radioButtonInit = QtWidgets.QRadioButton(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.radioButtonInit.setFont(font)
        self.radioButtonInit.setObjectName("radioButtonInit")
        self.horizontalLayout_3.addWidget(self.radioButtonInit)
        self.radioButtonGoal = QtWidgets.QRadioButton(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.radioButtonGoal.setFont(font)
        self.radioButtonGoal.setObjectName("radioButtonGoal")
        self.horizontalLayout_3.addWidget(self.radioButtonGoal)
        self.radioButtonObstacles = QtWidgets.QRadioButton(AStar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.radioButtonObstacles.setFont(font)
        self.radioButtonObstacles.setObjectName("radioButtonObstacles")
        self.horizontalLayout_3.addWidget(self.radioButtonObstacles)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidgetResult = QtWidgets.QTableWidget(AStar)
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(0)
        self.tableWidgetResult.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidgetResult)
        self.label_row.setBuddy(self.spinBox_row)
        self.label_col.setBuddy(self.spinBox_col)

        self.retranslateUi(AStar)
        QtCore.QMetaObject.connectSlotsByName(AStar)
        AStar.setTabOrder(self.spinBox_row, self.spinBox_col)
        AStar.setTabOrder(self.spinBox_col, self.pushButtonGenerate)
        AStar.setTabOrder(self.pushButtonGenerate, self.pushButtonResult)
        AStar.setTabOrder(self.pushButtonResult, self.tableWidgetResult)

    def retranslateUi(self, AStar):
        AStar.setWindowTitle(QtWidgets.QApplication.translate("AStar", "A*迷宫算法", None, -1))
        self.label_row.setText(QtWidgets.QApplication.translate("AStar", "行数", None, -1))
        self.label_col.setText(QtWidgets.QApplication.translate("AStar", "列数", None, -1))
        self.pushButtonGenerate.setText(QtWidgets.QApplication.translate("AStar", "生成迷宫", None, -1))
        self.pushButtonResult.setText(QtWidgets.QApplication.translate("AStar", "寻找通路", None, -1))
        self.label_setting.setText(QtWidgets.QApplication.translate("AStar", "添加设置", None, -1))
        self.radioButtonInit.setText(QtWidgets.QApplication.translate("AStar", "牛郎", None, -1))
        self.radioButtonGoal.setText(QtWidgets.QApplication.translate("AStar", "织女", None, -1))
        self.radioButtonObstacles.setText(QtWidgets.QApplication.translate("AStar", "墙", None, -1))
