# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/josephus_circle.ui',
# licensing of './UI/josephus_circle.ui' applies.
#
# Created: Mon May 27 11:56:54 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_JosephusCircleFrame(object):
    def setupUi(self, JosephusCircleFrame):
        JosephusCircleFrame.setObjectName("JosephusCircleFrame")
        JosephusCircleFrame.resize(596, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/root/favicon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        JosephusCircleFrame.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(JosephusCircleFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(JosephusCircleFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelDataStructure = QtWidgets.QLabel(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.labelDataStructure.setFont(font)
        self.labelDataStructure.setObjectName("labelDataStructure")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelDataStructure)
        self.comboBox = QtWidgets.QComboBox(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_people = QtWidgets.QLabel(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_people.setFont(font)
        self.label_people.setObjectName("label_people")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_people)
        self.spinBox_people = QtWidgets.QSpinBox(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBox_people.setFont(font)
        self.spinBox_people.setObjectName("spinBox_people")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_people)
        self.label_times = QtWidgets.QLabel(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_times.setFont(font)
        self.label_times.setObjectName("label_times")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_times)
        self.spinBox_times = QtWidgets.QSpinBox(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBox_times.setFont(font)
        self.spinBox_times.setObjectName("spinBox_times")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_times)
        self.label_starter = QtWidgets.QLabel(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label_starter.setFont(font)
        self.label_starter.setObjectName("label_starter")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_starter)
        self.spinBox_starter = QtWidgets.QSpinBox(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBox_starter.setFont(font)
        self.spinBox_starter.setObjectName("spinBox_starter")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_starter)
        self.commitButton = QtWidgets.QPushButton(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.commitButton.setFont(font)
        self.commitButton.setObjectName("commitButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.commitButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout.addLayout(self.formLayout)
        self.labelResult = QtWidgets.QTextBrowser(JosephusCircleFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.horizontalLayout.addWidget(self.labelResult)
        self.labelDataStructure.setBuddy(self.comboBox)
        self.label_people.setBuddy(self.spinBox_people)
        self.label_times.setBuddy(self.spinBox_times)
        self.label_starter.setBuddy(self.spinBox_starter)

        self.retranslateUi(JosephusCircleFrame)
        QtCore.QMetaObject.connectSlotsByName(JosephusCircleFrame)
        JosephusCircleFrame.setTabOrder(self.comboBox, self.spinBox_people)
        JosephusCircleFrame.setTabOrder(self.spinBox_people, self.spinBox_times)
        JosephusCircleFrame.setTabOrder(self.spinBox_times, self.spinBox_starter)
        JosephusCircleFrame.setTabOrder(self.spinBox_starter, self.commitButton)
        JosephusCircleFrame.setTabOrder(self.commitButton, self.labelResult)

    def retranslateUi(self, JosephusCircleFrame):
        JosephusCircleFrame.setWindowTitle(QtWidgets.QApplication.translate("JosephusCircleFrame", "约瑟夫环", None, -1))
        self.labelDataStructure.setText(QtWidgets.QApplication.translate("JosephusCircleFrame", "选择数据结构", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("JosephusCircleFrame", "数组", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("JosephusCircleFrame", "链表", None, -1))
        self.label_people.setText(QtWidgets.QApplication.translate("JosephusCircleFrame", "人数", None, -1))
        self.label_times.setText(QtWidgets.QApplication.translate("JosephusCircleFrame", "报数周期", None, -1))
        self.label_starter.setText(QtWidgets.QApplication.translate("JosephusCircleFrame", "起始人", None, -1))
        self.commitButton.setText(QtWidgets.QApplication.translate("JosephusCircleFrame", "提交", None, -1))
        self.commitButton.setShortcut(QtWidgets.QApplication.translate("JosephusCircleFrame", "Return", None, -1))
